version: '3.5'

services:
  nest-app:
    build: .
    ports:
      - 3000:3000
    networks:
      - app-network
    volumes:
      - .:/usr/src/app
    depends_on: 
      - database

  nginx:
    build: nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - nest-app

  database:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/data/postgres
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
    networks:
      - app-network
    restart: unless-stopped

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge

volumes:
  postgres: